### ISSUE TITLE
Inlining incorrectly handles nested if statement

### ISSUE THREAD

**Issue by Kaleb-Reid** [bloodwiing/gdmaim#4]
I didn't notice before because it doesn't cause any errors to appear and everything seemed to work initially, but inlining will incorrectly handle the following method:
```
func _ready() -> void:
	if false:
		if true:
			pass
	elif true:
		print("intended branch")
```
If inlining is enabled, it will result in the following:
```
func _ready()->void:
	if false:if true:pass
	elif true:print("want to be here")
```
which will not actually execute the correct branch and print the statement, instead the ```elif true``` branches from the ```if true```.

**Comment by bloodwiing** [comment]
Is this with the latest main commit? I thought I fixed it with https://github.com/bloodwiing/gdmaim/commit/747f91446db691544417283734ab7e76b6366693

Could you provide a minimal reproducible example?

**Comment by Kaleb-Reid** [comment]
@bloodwiing Yes this is on main.

[mrp.zip](https://github.com/user-attachments/files/19936704/mrp.zip)

**Comment by bloodwiing** [comment]
Fixed, apparently I had forgotten to check `elif`, but it should follow same rules as `else`

**Comment by Kaleb-Reid** [comment]
@bloodwiing While that was a good catch, unfortunately it didn't fix my issue. If in the mrp I sent you add the fix and replace ```_ready()``` with
```
func _ready() -> void:
	if false:
		pass # <- only difference
		if true:
			pass
	elif true:
		print("intended branch")
```
then the result is
```
func _ready()->void:
	if false:pass;if true:pass
	elif true:print("intended branch")
```

**Comment by bloodwiing** [comment]
Well spotted, fixed

**Comment by Kaleb-Reid** [comment]
@bloodwing The change seems to conflict with the previous fix to not collapse lines with ```@warning_ignore()``` and others
```
var test: Dictionary[String, Callable] = {
	"test":
		func(_x: bool) -> void:
			if true:
				@warning_ignore("incompatible_ternary")
				return
}
```
gets turned into
```
var test:Dictionary[String,Callable]={"test":func(_x:bool)->void:if true:@warning_ignore("incompatible_ternary")return}
```
but it needs to be
```
var test:Dictionary[String,Callable]={"test":func(_x:bool)->void:if true:
	@warning_ignore("incompatible_ternary")return}
```

**Comment by bloodwiing** [comment]
Not sure how it would conflict, cause this just seems like it a coincidental support, but this was a present bug with lambdas and warning_ignore specifically. Fixed, but I don't have the other tests to ensure that I didn't break any other fix from before.

**Comment by Kaleb-Reid** [comment]
@bloodwiing It must've been coincidental because that's the only one I have in my project and the fix last time worked. I think the way that this is implemented now is hitting some kind of engine bug? This is making the output look like:
```
var test:Dictionary[String,Callable]={"test":func(_x:bool)->void:
	if true:@warning_ignore("incompatible_ternary")return}
```
but say it looks like this instead:
```
var test:Dictionary[String,Callable]={"test":func()->void:
	if false:@warning_ignore("incompatible_ternary")print("here")}
```
"here" still gets printed. I will probably look for / open an issue on the Godot repo for this. In this situation the solution is to put:
```
var test:Dictionary[String,Callable]={"test":func()->void:if false:
	@warning_ignore("incompatible_ternary")print("here")}
```
instead. Not sure if it is exclusive to lambdas or not.
